# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
registries:
  gradle-artifactory:
    type: nuget
    url: https://nuget.pkg.github.com/dlebansais/index.json
    username: dlebansais
    password: ${{secrets.PRIVATE_GITHUB_SOURCE}}
updates:
  - package-ecosystem: "nuget"
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
