# version format
version: v{build}

branches:
  only:
    - master
    - deployment

# Skipping commits with particular message or from specific user
skip_commits:
  message: "*[skip ci]*"

image: Visual Studio 2022

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input

environment:
  package_token:
    secure: oeB0vPa3ehegduJ/WnxLssnK6wiIc8MVx0lVYeiXKT6pIz9ZDQ4ioQ55g6GYz9dW
  opencover_version: 4.7.1221
  codecov_version: 0.2.4
  report_generator_version: 5.2.0
  csharp-format_version: 0.0.9

matrix:
  fast_finish: true     # set this flag to immediately finish build once one of the jobs fails.

before_build:
  - ps: (Get-Content nuget.config).replace('Insert token here', $env:package_token) | Set-Content nuget.config
  - nuget restore %APPVEYOR_PROJECT_NAME%.sln
  - nuget install GitCommitId -DependencyVersion Highest -OutputDirectory packages

configuration:
  - Release
  - Debug

build:
  project: $(APPVEYOR_PROJECT_NAME).sln

after_build:
  - nuget install Packager -DependencyVersion Highest -OutputDirectory packages # Install Packager
  - ps: $folder = Get-ChildItem -Path packages/Packager.* -Name | Out-String    # Get the installation folder (we don't know the actual version)
  - ps: $firstline = ($folder -split '\r\n')[0]                                 # Get rid of carriage-return
  - ps: $fullpath = ".\packages\$firstline\lib\net481\Packager.exe"             # Build full path
  - ps: $env:PACKAGER_PATH=$fullpath
  - '%PACKAGER_PATH% %CUSTOM_PACKAGER_OPTIONS%'                                 # Execute the packager: the output is nuget\%APPVEYOR_PROJECT_NAME%.nuspec
  - if exist nuget\%APPVEYOR_PROJECT_NAME%.nuspec nuget pack nuget\%APPVEYOR_PROJECT_NAME%.nuspec
  - '%PACKAGER_PATH% %CUSTOM_PACKAGER_OPTIONS% --debug'                         # Execute the packager: the output is nuget-debug\%APPVEYOR_PROJECT_NAME%-Debug.nuspec
  - if exist nuget-debug\%APPVEYOR_PROJECT_NAME%-Debug.nuspec nuget pack nuget-debug\%APPVEYOR_PROJECT_NAME%-Debug.nuspec
  - ps: |-
        $xml = [xml](Get-Content .\$env:APPVEYOR_PROJECT_NAME\$env:APPVEYOR_PROJECT_NAME.csproj)
  - ps: $version=$xml.Project.PropertyGroup.Version
  - ps: set version_tag v$version
  - ps: $version_tag=$version_tag.Trim()
  - ps: $env:VERSION_TAG=$version_tag
  - echo Version is "%VERSION_TAG%"

before_test:
  - nuget install OpenCover -Version %opencover_version% -OutputDirectory packages
  - nuget install CodecovUploader -Version %codecov_version% -OutputDirectory packages
  - |-
    printf "dotnet test ./Test/%APPVEYOR_PROJECT_NAME%.Test/bin/x64/%CONFIGURATION%/net8.0-windows7.0/%APPVEYOR_PROJECT_NAME%.Test.dll -l console;verbosity=detailed\n" > runtests.bat
    printf "dotnet test ./Test/%APPVEYOR_PROJECT_NAME%.Test/bin/x64/%CONFIGURATION%/net481/%APPVEYOR_PROJECT_NAME%.Test.dll -l console;verbosity=detailed\n" >> runtests.bat
  - |-
    printf "@echo ************************************************************** Starting Tests..\n" > runtests1.bat
    printf "call runtests.bat\n" >> runtests1.bat
  - |-
    printf ".\packages\OpenCover.%opencover_version%\Tools\OpenCover.Console.exe -register:user -returntargetcode -target:\x25\x31 -mergeoutput -output:""Coverage-%APPVEYOR_PROJECT_NAME%"".xml\n" > opencover.bat

test_script:
  - opencover.bat runtests1.bat

after_test:
  - ps: Get-Content Coverage-*.xml -Head 3
  - if '%APPVEYOR_REPO_BRANCH%' == 'master' .\packages\CodecovUploader.%codecov_version%\Tools\codecov.exe -f "Coverage-%APPVEYOR_PROJECT_NAME%.xml"
  - nuget install ReportGenerator -Version %report_generator_version% -OutputDirectory packages
  - if '%APPVEYOR_REPO_BRANCH%' == 'master' .\packages\ReportGenerator.%report_generator_version%\Tools\net8.0\ReportGenerator.exe "-reports:Coverage-%APPVEYOR_PROJECT_NAME%.xml" -targetdir:.\CoverageReports "-assemblyfilters:-Microsoft*;+%APPVEYOR_PROJECT_NAME%" "-filefilters:-*.g.cs" "-reporttypes:textsummary"
  - ps: |-
        $summary = Get-Content .\CoverageReports\Summary.txt
        $pattern = 'Branch coverage: 200%'
        $summary -Contains $pattern

artifacts:
  - path: $(APPVEYOR_PROJECT_NAME)-Debug.*.nupkg
    name: $(APPVEYOR_PROJECT_NAME)-Package-Debug
  - path: $(APPVEYOR_PROJECT_NAME).*.nupkg
    name: $(APPVEYOR_PROJECT_NAME)-Package-Release

deploy:
  - provider: GitHub
    release: $(VERSION_TAG)
    description: 'Automatic deployment'
    auth_token:
      secure: 8IyH+0A5FwE96xWDzhXQH5zxg49+0MhTd25bUTMcc6qePhZcVmaVd6i0bsM2tT1Q
    artifact: $(APPVEYOR_PROJECT_NAME)-Package-Release
    draft: false
    prerelease: false
    on:
      branch: deployment
      configuration: Release
  - provider: GitHub
    release: $(VERSION_TAG)
    description: 'Automatic deployment'
    auth_token:
      secure: 8IyH+0A5FwE96xWDzhXQH5zxg49+0MhTd25bUTMcc6qePhZcVmaVd6i0bsM2tT1Q
    artifact: $(APPVEYOR_PROJECT_NAME)-Package-Debug
    draft: false
    prerelease: false
    on:
      branch: deployment
      configuration: Debug
  - provider: NuGet
    artifact: $(APPVEYOR_PROJECT_NAME)-Package-Release
    skip_symbols: true
    api_key:
      secure: gmxGdYXre5ryN4BlRVa0qJM++Sw86tRiKT4hpH5/OTK2daKRpeiOxFsVWpPLGJ+e
    on:
      branch: deployment
      configuration: Release
  - provider: NuGet
    server: https://nuget.pkg.github.com/dlebansais/index.json
    symbol_server: https://nuget.pkg.github.com/dlebansais/index.json
    artifact: $(APPVEYOR_PROJECT_NAME)-Package-Debug
    username: dlebansais
    api_key:
      secure: P1otXPxREK8T2L9vw4vpvvpXYlMyCTGa/iQIfuXtr4mjOFZBYR83Aie3hTZotfOu
    on:
      branch: deployment
      configuration: Debug
  - provider: NuGet
    server: https://nuget.pkg.github.com/dlebansais/index.json
    artifact: $(APPVEYOR_PROJECT_NAME)-Package-Release
    skip_symbols: true
    username: dlebansais
    api_key:
      secure: P1otXPxREK8T2L9vw4vpvvpXYlMyCTGa/iQIfuXtr4mjOFZBYR83Aie3hTZotfOu
    on:
      branch: deployment
      configuration: Release
